services:
  backend_telegram_bot:
    image: ckala62rus/telegrambotrk-backend_telegram_bot:latest
    container_name: backend_telegram_bot
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: bash -c "alembic upgrade head && python app.py"
    ports:
      - "8001:8001"
    volumes:
      - ./src:/src
      - ./.env:/src/.env
    depends_on:
      - db_telegram_bot
    networks:
      - my-proxy-net
      - default

  db_telegram_bot:
    container_name: db_telegram_bot
    image: postgres:14.1-alpine
#    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata_telegram_bot:/var/lib/postgresql/data
      - ./docker/backup/postgres:/tmp/backup
    env_file:
      - ./.env
    networks:
      - my-proxy-net
      - default

  pgadmin_telegram_bot:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_fastapi_2024
    env_file:
      - ./.env
    ports:
      - "5050:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db_telegram_bot

volumes:
  pgdata_telegram_bot:
    name: pgdata_telegram_bot

networks:
  my-proxy-net:
    external:
      name: giveItANamePlease
